### PR TITLE
Add Robert Feranec's YouTube channel

### PR DESCRIPTION
**Pull request by robertferanec**
Just crossed 2 million views and almost 12 000 subscribers. I know it's my own channel, but people may find it useful.

### CODE REVIEW

**Comment by joaoantoniocardoso** [comment]
@kasbah There is some problem with this one?

**Comment by kasbah** [comment]
It's someone self-promoting, which is not a great start. It could be ok if the content is good but I haven't actually had a chance to check out any of the videos.

**Comment by stevestock** [comment]
@kasbah This is the guy that teaches the courses on https://academy.fedevel.com.  High quality youtube content, and high quality design courses.  I recommend adding both.

**Comment by kasbah** [comment]
Thanks @stevestock, if it has your endorsement I am happy for it to be added.

**Pull request merged**
