### PR TITLE
add link to Simple Electronics Wiki

### PR DESCRIPTION
**Pull request by robkam**

### CODE REVIEW

**Comment by kasbah** [comment]
Hmm, looks like a great start but there are loads of dead links. Probably makes it a frustrating place for a beginner at the moment.

**Comment by robkam** [comment]
I'm working on it. Maybe another year and it'll be ready, (unless other people start editing).

**Comment by kasbah** [comment]
Fair enough, could you write a message on here when it has a bit more content please? I realize it's a bit of a bootstrapping problem for you (people have to know about it to contribute to make it better) but I just don't think we would be doing beginners a service by linking to it now.

**Comment by robkam** [comment]
That's okay, I'll get back to you when it has more content ...

**Comment by kasbah** [comment]
Ok, thanks, closing till then.

**Pull request closed without merging**
