### PR TITLE
Add tscircuit under free EDA tools

### PR DESCRIPTION
**Pull request by seveibar**
Github repository: https://github.com/tscircuit/tscircuit

### CODE REVIEW

**Comment by seveibar** [comment]
@vinceh121 I think people are definitely using it for documentation (e.g. producing schematic renderings), but it does produce gerbers, I produced a full functional circuit [(shown here)](https://x.com/seveibar/status/1785128472714817741), there are also some interactive components [e.g. dragging and dropping footprints around](https://x.com/seveibar/status/1786808695634157569). Ideally it becomes a viable alternative/companion to kicad in the long run.

That said, I'm happy to have it listed anywhere, happy to change this PR to move to documentation if you'd prefer, thanks for the quick response and the repo :)

**Comment by seveibar** [comment]
@vinceh121 bump! Happy to move into documentation, but I swear [I made a full circuit with tscircuit!](https://x.com/seveibar/status/1785128472714817741)

**Comment by vinceh121** [comment]
Apologies, didn't mean to keep you waiting.

I've moved the line under documentation, as I think that when people look for EDAs, they are looking for the more classic full-featured GUI, and not a "circuit-as-code" solution.

Of course, not to undermine your project, I think it looks very promising, and once you have implemented more GUI features for design, we'll happily move the bullet-point line under EDAs :)

**Comment by seveibar** [comment]
cheers i appreciate it!

**Pull request merged**
