### PR TITLE
Add GC-Prevue

### PR DESCRIPTION
**Pull request by Timmmm**
Normally I would prefer using open source programs, but GC-Prevue is a) actually very good, and b) renders some gerbers more correctly than gerbv, e.g. those produced by DesignSpark PCB.

### CODE REVIEW

**Comment by kasbah** [comment]
Hmmm just tried installing this with Wine and it doesn't work so I have no way easy way of testing right now. 

What kind of Gerbers does this handle better than the others, are there any examples I could try if I set it up in a VM?

**Comment by Timmmm** [comment]
Here's one: [remote_control_-_Top_Copper.gbr.zip](https://github.com/monostable/awesome-electronics/files/749911/remote_control_-_Top_Copper.gbr.zip)

Apparently the issue arises because DesignsparkPCB doesn't close polygons, and the behaviour for that is undefined in the gerber spec. But every manufacturer I've sent them to makes them like GC-Prevue renders them (with the polygons implicitly closed), and not how Gerbv et al. render them.

**Comment by stevestock** [comment]
@kasbah This is one of the gerber viewers recommended on the /r/PrintedCircuitBoard/ sidebar.  It has a lot of features, including opening up multiple zips at once, and graphical file merge. Closed source, but reasonably priced for a professional gerber viewer. It no longer has a free version, so the description needs to change, but I recommend adding it

**Comment by kasbah** [comment]
:+1:

**Pull request merged**
